//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock_Delivery_App_Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditPayment
    {
        public int id { get; set; }
        public Nullable<int> paid_amount { get; set; }
        public string payment_date { get; set; }
        public string payment_type { get; set; }
        public Nullable<int> credit_id { get; set; }
    }
}
