//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock_Delivery_App_Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributorProduct
    {
        public int id { get; set; }
        public Nullable<int> saleprice_for_shopkeeper { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> distributor_id { get; set; }
        public Nullable<int> total_cartons { get; set; }
    }
}
