//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock_Delivery_App_Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int id { get; set; }
        public Nullable<int> no_of_stars { get; set; }
        public Nullable<int> reviewer_id { get; set; }
        public Nullable<int> reciever_id { get; set; }
        public Nullable<int> oid { get; set; }
    }
}
