//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock_Delivery_App_Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnProduct
    {
        public int id { get; set; }
        public string reason { get; set; }
        public string detail { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<int> price_per_pack { get; set; }
        public Nullable<int> seller_id { get; set; }
        public Nullable<int> buyer_id { get; set; }
        public string status { get; set; }
    }
}
