//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock_Delivery_App_Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserOrder
    {
        public int id { get; set; }
        public string order_status { get; set; }
        public string order_type { get; set; }
        public Nullable<int> order_state { get; set; }
        public Nullable<int> total_amount { get; set; }
        public string order_place_date { get; set; }
        public string order_deliver_date { get; set; }
        public Nullable<int> seller_id { get; set; }
        public Nullable<int> buyer_id { get; set; }
    }
}
