//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock_Delivery_App_Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorProduct
    {
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<int> qty_in_carton { get; set; }
        public Nullable<int> saleprice_per_carton { get; set; }
        public string category { get; set; }
        public string company_name { get; set; }
        public Nullable<int> threshold { get; set; }
        public string image { get; set; }
        public Nullable<int> vendor_id { get; set; }
        public Nullable<int> total_cartons { get; set; }
    }
}
